apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-deployment
  namespace: survey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: survey
  template:
    metadata:
      labels:
        app: survey
    spec:
      shareProcessNamespace: true
      containers:
      - name: docker-survey
        image: rhemsjapan/docker-survey:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
  strategy:
    type: Recreate