apiVersion: v1
kind: Pod
metadata:
  name: survey
  namespace: survey
spec:
  shareProcessNamespace: true
  containers:
  - name: docker-survey
    image: rhemsjapan/docker-survey:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
  restartPolicy: Never

---

# apiVersion: v1
# kind: Namespace
# metadata:
#   name: survey

# ---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: survey
  name: docker-survey-role
rules:
- apiGroups:
  - apps
  - extensions
  resources:
  - "*"
  verbs:
  - "*"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-reader-rolebinding
  namespace: survey
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: docker-survey-role
subjects:
- kind: ServiceAccount
  name: docker-survey-sa
  namespace: survey